routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('vaamUsers', 'VaamUsersController');
Route::post('vaamUsers/store', 'VaamUsersController@store')->name('vaam.store');
Route::get('vaamUsers/edit/{id}', 'VaamUsersController@edit')->name('vaam.edit');
Route::post('vaamUsers/update/{id}', 'VaamUsersController@update')->name('vaam.update');
Route::get('vaamUsers/delete/{id}', 'VaamUsersController@destroy')->name('vaam.delete');

Route::resource('commodity', 'CommodityController');
Route::post('commodity/store', 'CommodityController@store')->name('commodity.store');
Route::get('commodity/edit/{id}', 'CommodityController@edit')->name('commodity.edit');
Route::post('commodity/update/{id}', 'CommodityController@update')->name('commodity.update');
Route::get('commodity/delete/{id}', 'CommodityController@destroy')->name('commodity.delete');


Route::resource('commodity-category', 'CommoditycategoryController');
Route::get('commodity-category/create/{id}', 'CommoditycategoryController@create')->name('commodity.category.create');
Route::post('commodity-category/store', 'CommoditycategoryController@store')->name('commodity.category.store');
Route::get('commodity-category/edit/{id}', 'CommoditycategoryController@edit')->name('commodity.category.edit');
Route::post('commodity-category/update/{id}', 'CommoditycategoryController@update')->name('commodity.category.update');
Route::get('commodity-category/delete/{id}', 'CommoditycategoryController@destroy')->name('commodity.category.delete');

Route::resource('vendor', 'VendorController');
Route::post('vendor/store', 'VendorController@store')->name('vendor.store');
Route::get('vendor/edit/{id}', 'VendorController@edit')->name('vendor.edit');
Route::post('vendor/update/{id}', 'VendorController@update')->name('vendor.update');
Route::get('vendor/delete/{id}', 'VendorController@destroy')->name('vendor.delete');

Route::resource('customer', 'CustomerController');
Route::post('customer/store', 'CustomerController@store')->name('customer.store');
Route::get('customer/edit/{id}', 'CustomerController@edit')->name('customer.edit');
Route::post('customer/update/{id}', 'CustomerController@update')->name('customer.update');
Route::get('customer/delete/{id}', 'CustomerController@destroy')->name('customer.delete');

Route::resource('expanse', 'ExpanseController');
Route::post('expanse/store', 'ExpanseController@store')->name('expanse.store');
Route::get('expanse/edit/{id}', 'ExpanseController@edit')->name('expanse.edit');
Route::post('expanse/update/{id}', 'ExpanseController@update')->name('expanse.update');
Route::get('expanse/delete/{id}', 'ExpanseController@destroy')->name('expanse.delete');

Route::resource('purchase', 'PurchasemgmController');
Route::post('purchase/store', 'PurchasemgmController@store')->name('purchase.store');
Route::get('purchase/edit/{id}', 'PurchasemgmController@edit')->name('purchase.edit');
Route::post('purchase/update/{id}', 'PurchasemgmController@update')->name('purchase.update');
Route::get('purchase/delete/{id}', 'PurchasemgmController@destroy')->name('purchase.delete');
Route::get('purchase/getpurchase/{id}', 'PurchasemgmController@getpurchase')->name('purchase.getpurchase');
Route::get('purchase/getpurchaseVendor/{id}', 'PurchasemgmController@getpurchaseVendor')->name('purchase.getpurchase');
Route::get('purchase/getpurchasecustomer/{id}', 'PurchasemgmController@getpurchasecustomer')->name('purchase.getpurchase');
Route::get('purchase/getpurchasecommodity/{id}', 'PurchasemgmController@getpurchasecommodity')->name('purchase.getpurchasecommodity');
Route::get('purchase/getcomapnyUser/{id}', 'PurchasemgmController@getcomapnyUser')->name('purchase.getcomapnyUser');


Route::resource('sales', 'SalesController');
Route::post('sales/store', 'SalesController@store')->name('sales.store');
Route::get('sales/edit/{id}', 'SalesController@edit')->name('sales.edit');
Route::post('sales/update/{id}', 'SalesController@update')->name('sales.update');
Route::get('sales/delete/{id}', 'SalesController@destroy')->name('sales.delete');
Route::get('sales/getpurchase/{id}', 'SalesController@getpurchase')->name('sales.getpurchase');
Route::get('sales/getpurchasecustomer/{id}', 'SalesController@getpurchasecustomer')->name('sales.getpurchase');
Route::get('sales/getcurrentcommodity/{id}', 'SalesController@getcurrentcommodity')->name('sales.getcurrentcommodity');
Route::get('sales/getCustomer/{id}', 'SalesController@getCustomer')->name('sales.getCustomer');
Route::get('sales/getstock/{id}', 'SalesController@getstock')->name('sales.getstock');
Route::get('sales/checkStockQty/{id}', 'SalesController@checkStockQty')->name('sales.checkStockQty');


Route::get('purchaseReport', 'ReportController@purchaseReport')->name('report.purchase');

Route::resource('producation', 'ProducationController');
Route::post('producation/store', 'ProducationController@store')->name('producation.store');
Route::get('producation/delete/{id}', 'ProducationController@destroy')->name('producation.delete');
Route::get('producation/getcommoditycategory/{id}', 'ProducationController@getcommoditycategory')->name('producation.getcommoditycategory');
Route::get('producation/getcurrentcommodity/{id}', 'ProducationController@getcurrentcommodity')->name('producation.getcurrentcommodity');

Route::resource('package', 'PackageController');
Route::post('package/store', 'PackageController@store')->name('package.store');
Route::get('package/delete/{id}', 'PackageController@destroy')->name('package.delete');
Route::get('package/getcommoditycategory/{id}', 'PackageController@getcommoditycategory')->name('package.getcommoditycategory');
Route::get('package/getcurrentcommodity/{id}', 'PackageController@getcurrentcommodity')->name('package.getcurrentcommodity');

app/Models/Producation.php
<?php

namespace App\Models;
use App\Models\StockMgmt;
use Illuminate\Database\Eloquent\Model;

class Producation extends Model
{
    protected $table = 'producations';
    protected $primaryKey = 'id';
    protected $guarded = [];
    public $timestamps = true;


    public function stockMgmts(){

        return $this->hasOne('App\Models\StockMgmt', 'producation_id', 'id');
    }
}

app/Http/Controllers/ProducationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Commodity;
use App\Models\Commodity_category;
use App\Http\Requests\ProducationStoreRequest;
use App\Http\Requests\UpdateProducationStoreRequest;
use App\Models\Producation;
use App\Models\StockMgmt;
use Illuminate\Http\Request;
use Exception;

use Illuminate\Support\Facades\Log;

class ProducationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $recodes = Producation::paginate(15);
        return view('producation.index',['recodes' => $recodes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $commodity = Commodity::get();
        //$commodityCategory = Commodity_category::where('name','raw')->get();
        return view('producation.create',compact('commodity'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProducationStoreRequest $request)
    {

        try {
            $validated = $request->validated();

            if(!empty($validated)){
                $users = new Producation();

                        $data['commodity_id'] = $request->commodity_id;
                        $data['commodity_category_id'] = $request->commodity_category_id;
                        $data['date'] = $request->date;
                        $data['quantity'] = $request->quantity;

                        $data['created_at'] = date('Y-m-d H:i:s');
                        $data['updated_at'] = date('Y-m-d H:i:s');

                        $users->insert($data);

                        //Stock Managegment

                        $checkValue = StockMgmt::where('commodity_id',$request->commodity_id)
                        ->where('commodity_category_id',$request->commodity_category_id)
                        ->first();

                        if($checkValue->production_stock == 0){
                            $producation_stock = $request->quantity;
                        }else{
                            $producation_stock = $checkValue->production_stock + $request->quantity;
                        }
                        $currentPurchaseStock = $checkValue->purchase_stock - $request->quantity;
                            if(isset($checkValue)){
                            $stockData['purchase_stock'] = $currentPurchaseStock;
                            $stockData['production_stock'] = $producation_stock;
                            $stockData['updated_at'] = date('Y-m-d H:i:s');
                            StockMgmt::where('id',$checkValue->id)->update($stockData);
                            }


                        Log::info('Sussfully added');
                        toastr()->success('Data has been saved successfully!');



            }else{
                throw new Exception("Something went wrong please try again");
            }

          }

          //catch exception
          catch(Exception $e) {
            Log::error($e->getMessage());
            toastr()->error('Something went wrong please try again');
            echo 'Message: ' .$e->getMessage();
          }
          return redirect('producation');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Producation  $producation
     * @return \Illuminate\Http\Response
     */
    public function show(Producation $producation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Producation  $producation
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Producation  $producation
     * @return \Illuminate\Http\Response
     */
    public function update($request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Producation  $producation
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            if(!empty($id)){
                $deleteUser = Producation::find($id);

                $deleteStock = StockMgmt::where('commodity_id',$deleteUser->commodity_id)
                ->where('commodity_category_id',$deleteUser->commodity_category_id)
                ->first();

                $finalProductionStock = $deleteStock->production_stock - $deleteUser->quantity;
                $finalpurchesStock = $deleteStock->purchase_stock + $deleteUser->quantity;

                $stockData['purchase_stock'] = $finalpurchesStock;
                $stockData['production_stock'] = $finalProductionStock;
                $stockData['updated_at'] = date('Y-m-d H:i:s');
                StockMgmt::where('id',$deleteStock->id)->update($stockData);

                $deleteUser->delete();
                Log::info('successfully deleted ');
                toastr()->success('Data has been deleted successfully!');
            }else{
                toastr()->error('Something went wrong please try again');
            }

          }

          //catch exception
          catch(Exception $e) {
            Log::error($e->getMessage());
            toastr()->error('Something went wrong please try again');
            echo 'Message: ' .$e->getMessage();
          }
          return redirect('producation');
    }
    public function getcommoditycategory($id){

        $commodity = Commodity::where('id',$id)->first();
        $commodityCategory = Commodity_category::where('commodity_id',$commodity->id)
        // ->where(function($query) {
        //     $query->where('name', 'raw');
        // })
        ->get();
        return response()->json(["result" => "success", "status" => 200, 'html' => $commodityCategory]);


    }

    public function getcurrentcommodity($id){


        $str_arr = preg_split ("/\,/", $id);

        $commodity_id = $str_arr[0];
        $commodity_category_id = $str_arr[1];

        $commodityCategory = StockMgmt::where('commodity_id',$commodity_id)
        ->where('commodity_category_id', $commodity_category_id)
        ->get();

        return response()->json(["result" => "success", "status" => 200, 'html' => $commodityCategory]);


    }
}

resources/views/producation/create.blade.php
@extends('admin.main')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Producation</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="producationForm" action="{{ route('producation.store') }}" id="validationProducation" class="form-horizontal" method="POST">

                @csrf
                @method('POST')
               @include('producation.form')
            </form>
        </div>
    </div>
</div>
</div>
</div>
</div>

@endsection

resources/views/producation/edit.blade.php
@extends('admin.main')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Producation</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id="producationForm" action="{{ route('producation.update', ['id' => $user->id]) }}" class="form-horizontal" method="POST">

                @csrf
                @method('POST')
               @include('producation.form')
            </form>
        </div>
    </div>
</div>
</div>
</div>
</div>

@endsection

resources/views/producation/form.blade.php
              <div class="card-body">
                      <div class="form-group @if ($errors->has('commodity_id')) has-error @endif">
                      <label for="commodity_id">Commodity</label>

                      <select  name="commodity_id" id="producation_commodity_id" class="form-control">
                        <option selected disabled>Please select Commodity</option>
                        @foreach ($commodity as $key => $value)
                        <option value="{{ $value->id }}"
                        {{ !empty(old('commodity_id')) && old('commodity_id') == $value->id
                            ? 'selected="selected"'
                            : ((!empty($user) && !empty($user->commodity_id)) && $user->commodity_id == $value->id
                                ? 'selected="selected"'
                                : "")
                        }}>{{ $value->name }}</option>
                    @endforeach

                    </select>
                    @if ($errors->has('commodity_id'))
                        <span class="text-danger">{{ $errors->first('commodity_id') }}</span>
                    @endif


                    </div>

                    <div class="form-group @if ($errors->has('commodity_category_id')) has-error @endif">
                        <label for="commodity_category_id">Commodity Quality</label>

                        <select  name="commodity_category_id" id="producation_commodity_category_id" class="form-control producation_commodity_category_id">
                          <option selected disabled>Please select Commodity Quality</option>

                          @if(isset($commodityCategory))
                          @foreach ($commodityCategory as $key => $value)
                          <option value="{{ $user->id }}"
                          {{ !empty(old('commodity_category_id')) && old('commodity_category_id') == $value->id
                              ? 'selected="selected"'
                              : ((!empty($user) && !empty($user->commodity_category_id)) && $user->commodity_category_id == $value->id
                                  ? 'selected="selected"'
                                  : "")
                          }}>{{ $value->name }}</option>
                            @endforeach
                        @endif

                      </select>
                      @if ($errors->has('commodity_category_id'))
                          <span class="text-danger">{{ $errors->first('commodity_category_id') }}</span>
                      @endif


                      </div>

                      <div class="form-group @if ($errors->has('date')) has-error @endif">
                        <label for="date">Date:</label>
                        <input type="text" name="date" id="date" class="form-control datetimepicker-input" value="{{ !empty(old('date')) ? old('date') : ((!empty($user) && !empty($user->date)) ? $user->date : "") }}"/>
                          @if ($errors->has('date'))
                        <span class="text-danger">{{ $errors->first('date') }}</span> @endif
                      </div>

                    <div class="form-group @if ($errors->has('quantity')) has-error @endif">
                        <label class="col-12 float-left" for="quantity">Quantity</label>
                        <div class="col-10 float-left">
                        <input type="text" class="form-control producationQuantity" name="quantity" id="quantity" placeholder="Enter quantity"
                        value="{{ !empty(old('quantity')) ? old('quantity') : ((!empty($user) && !empty($user->quantity)) ? $user->quantity : "") }}"  /> @if ($errors->has('quantity'))
                          <span class="text-danger">{{ $errors->first('quantity') }}</span> @endif
                        </div>
                        <div class="col-2 float-left">
                            <input type="text" readonly class="form-control" name="currentQuantity" id="currentQuantity"

                        value=" @if(isset($user->stockMgmts->purchase_stock)) {{ $user->stockMgmts->purchase_stock }} @else {{ !empty(old('currentQuantity')) ? old('currentQuantity') : ((!empty($user) && !empty($user->stockMgmts->purchase_stock)) ? $user->stockMgmts->purchase_stock : "") }} @endif"   /> @if ($errors->has('currentQuantity'))
                              <span class="text-danger">{{ $errors->first('currentQuantity') }}</span> @endif

                        </div>
                    </div>


            </div>

              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>

resources/views/producation/index.blade.php
@extends('admin.main')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
    <div class="container-fluid">
      <div class="row">
      <div class="col-12">
        <div class="card">
            <div class="card-header">

            <a class="btn btn-primary float-right" href="{{ url('producation/create') }}">New Production</a>
            </div>
            <!-- /.card-header -->

            <div class="card-body">
                <table id="vaamUsers" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                  <th>Commodity</th>
                  <th>Commodity category</th>
                  <th>Date</th>
                  <th>Quantity</th>
                  <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($recodes as $recode)
                    <tr>
                        <?php $recodeInfo =  \App\Models\Commodity::where('id',$recode->commodity_id)->first(); ?>
                        <td>{{ $recodeInfo->name }}</td>
                        <?php $commdityCategoryInfo =  \App\Models\Commodity_category::where('id',$recode->commodity_category_id)->first(); ?>
                        <td>{{ $commdityCategoryInfo->name }}</td>
                        <td> {{ $recode->date }}</td>
                        <td> {{ $recode->quantity }}</td>
                        <td>
                            <a href="{{ route('producation.delete', ['id' => $recode->id]) }}"><i class="fa fa-trash-alt"></i></a></td>
                    </tr>

                @endforeach

                  </tbody>

                </table>
                {{ $recodes->links() }}
              </div>

            <!-- /.card-body -->
          </div>
      </div>
      </div>
    </div>
</div>
</div>
</div>
@endsection